import { NavBar } from "@/components/navbar/navbar";
import { ThemeProvider } from "@/components/theme-provider/theme-provider";
import { i18nConfig } from "@/libs/i18n-next/i18n-config";
import { I18NextProvider } from "@/libs/i18n-next/i18n-next-provider";
import { dir } from "i18next";
import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import { cookies } from "next/headers";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const locale = (await cookies()).get(i18nConfig.cookieName)?.value;
  const direction = dir(locale);

  return (
    <I18NextProvider>
      <html suppressHydrationWarning lang={locale} dir={direction}>
        <body
          className={`${geistSans.variable} ${geistMono.variable} antialiased`}
        >
          <ThemeProvider
            attribute="class"
            defaultTheme="system"
            enableSystem
            disableTransitionOnChange
          >
            <NavBar />
            {children}
          </ThemeProvider>
        </body>
      </html>
    </I18NextProvider>
  );
}
